# Generated by Django 4.1.1 on 2022-09-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='article', verbose_name='Imagen'),
        ),
    ]
